#!/bin/bash
# Manual DigitalOcean Deployment Script
# Since CLI GitHub auth is failing, deploy manually

echo "============================================"
echo "MegiLance Unified Deployment"
echo "============================================"
echo ""
echo "❌ CLI Authentication Issue Detected"
echo "   GitHub token doesn't have access to repo"
echo ""
echo "✅ SOLUTION: Use DigitalOcean Web Console"
echo ""
echo "📋 STEPS:"
echo ""
echo "1. Go to: https://cloud.digitalocean.com/apps"
echo ""
echo "2. Click 'Create App'"
echo ""
echo "3. Select GitHub:"
echo "   Repository: ghulam-mujtaba5/MegiLance"
echo "   Branch: main"
echo "   Auto-deploy: ON"
echo ""
echo "4. When prompted for deployment settings:"
echo "   - Source: Monorepo (has both frontend & backend)"
echo "   - Click 'Next'"
echo ""
echo "5. Go to 'App Spec' tab and click 'Edit'"
echo ""
echo "6. Copy-paste the ENTIRE content of .do/app.yaml:"
echo ""
cat .do/app.yaml
echo ""
echo "7. Click 'Save' then 'Deploy'"
echo ""
echo "8. Monitor deployment:"
echo "   ✓ Frontend (web) - port 3000"
echo "   ✓ Backend (api) - port 8000"
echo "   ✓ Health checks - all green"
echo ""
echo "9. Verify after 5-10 minutes:"
echo "   Frontend: https://megilance.ondigitalocean.app"
echo "   Backend: https://megilance.ondigitalocean.app/api/health/live"
echo ""
