import type { Metadata, Viewport } from 'next';
import './globals.css';
import '../styles/themes/light.css';
import '../styles/themes/dark.css';
import '../styles/tokens.css';
import './styles/theme.css';

import ClientRoot from './ClientRoot';
import GoogleAnalytics from './components/Analytics/GoogleAnalytics';
import {
  BASE_URL,
  SITE_NAME,
  SITE_DESCRIPTION,
  SITE_TAGLINE,
  buildWebSiteJsonLd,
  buildOrganizationJsonLd,
  buildSoftwareAppJsonLd,
  buildSiteNavigationJsonLd,
  buildAggregateRatingJsonLd,
  buildPageFactsJsonLd,
  jsonLdScriptProps,
  SEO_KEYWORDS,
} from '../lib/seo';

// ── Structured data for Google rich results & AI Search Engines ─────────
// 1. WebSite – Enables Sitelinks SearchBox in Google SERP
// 2. Organization – Shows brand Knowledge Panel with logo + social links
// 3. SoftwareApplication – App rich result with rating
// 4. SiteNavigationElement – Helps Google understand main nav for sitelinks
// 5. PageFacts – Direct factual facts for AI Search Bots (GEO / AEO)
const websiteJsonLd = buildWebSiteJsonLd();
const orgJsonLd = buildOrganizationJsonLd();
const appJsonLd = buildSoftwareAppJsonLd();
const navJsonLd = buildSiteNavigationJsonLd();
const pageFactsJsonLd = buildPageFactsJsonLd([
  { property: 'Platform Commission Fee', value: '0% (100% Free Launch)' },
  { property: 'Client Service Fee', value: '0%' },
  { property: 'Talent Matching Engine', value: 'Proprietary AI & Machine Learning' },
  { property: 'Payment Protection', value: 'Milestone Escrow via Stripe' },
  { property: 'Global Coverage', value: '150+ Countries Worldwide' },
]);

// Flatten top keywords for root metadata (Semrush-validated, highest volume first)
const rootKeywords = [
  ...SEO_KEYWORDS.brand,
  ...SEO_KEYWORDS.transactional.slice(0, 12),
  ...SEO_KEYWORDS.informational.slice(0, 8),
  ...SEO_KEYWORDS.longTail.slice(0, 6),
  ...SEO_KEYWORDS.technology.slice(0, 4),
  ...SEO_KEYWORDS.features.slice(0, 4),
];

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: `${SITE_NAME} — AI Freelance Marketplace & Freelancer Platform`,
    template: `%s | ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  keywords: rootKeywords,
  manifest: '/manifest.json',
  icons: {
    icon: [
      { url: '/icon.svg', type: 'image/svg+xml' },
      { url: '/icons/icon-144x144.png', sizes: '144x144', type: 'image/png' },
      { url: '/icons/icon-192x192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-192x192.svg', sizes: '192x192', type: 'image/svg+xml' },
      { url: '/icons/icon-512x512.svg', sizes: '512x512', type: 'image/svg+xml' },
    ],
    shortcut: '/icon.svg',
    apple: [
      { url: '/icons/icon-192x192.png', sizes: '180x180', type: 'image/png' },
    ],
  },
  authors: [{ name: 'MegiLance Team', url: 'https://megilance.site' }],
  creator: 'MegiLance',
  publisher: 'MegiLance',
  applicationName: 'MegiLance',
  category: 'Business',
  classification: 'Freelance Marketplace',
  referrer: 'origin-when-cross-origin',
  
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: BASE_URL,
    siteName: SITE_NAME,
    title: `${SITE_NAME} | Free AI Tools for Freelancers & Clients | Freelance Marketplace`,
    description: 'Free AI tools to price freelance projects, write proposals, calculate rates, and plan work. Plus a freelance marketplace with milestone escrow payments and 7-factor talent matching.',
    countryName: 'Worldwide',
    // Images auto-generated by app/opengraph-image.tsx (Next.js file convention)
  },
  
  twitter: {
    card: 'summary_large_image',
    site: '@megilance',
    creator: '@megilance',
    title: `${SITE_NAME} | Free AI Tools & Freelance Marketplace`,
    description: 'Free AI tools for project pricing, proposals, and rates, connected to a freelance marketplace with milestone escrow protection.',
    // Images auto-generated by app/twitter-image.tsx (Next.js file convention)
  },
  
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  
  verification: {
    google: process.env.GOOGLE_SITE_VERIFICATION,
    yandex: process.env.YANDEX_VERIFICATION,
    other: {
      'msvalidate.01': process.env.BING_VERIFICATION || '',
      'p:domain_verify': process.env.PINTEREST_VERIFICATION || '',
    },
  },
  
  other: {
    'msapplication-TileColor': '#4573df',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
    'apple-mobile-web-app-title': SITE_NAME,
    'format-detection': 'telephone=no',
    'mobile-web-app-capable': 'yes',
    'msapplication-config': '/browserconfig.xml',
    'theme-color': '#4573df',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  viewportFit: 'cover',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#0b0f19' },
  ],
  colorScheme: 'light dark',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Google Analytics - FREE forever */}
        <GoogleAnalytics />
        
        {/* Preconnect to important third-party origins */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        
        {/* hreflang - single language site, set x-default */}
        <link rel="alternate" hrefLang="en" href="https://megilance.site" />
        <link rel="alternate" hrefLang="x-default" href="https://megilance.site" />
        
        {/* DNS prefetch for API */}
        <link rel="dns-prefetch" href="//api.stripe.com" />
        
        {/* RSS Feed for Blog - improves content discovery by search engines */}
        <link rel="alternate" type="application/rss+xml" title="MegiLance Blog" href="/blog/feed.xml" />
        
        {/* Structured Data for SEO – Google Rich Results */}
        <script {...jsonLdScriptProps(websiteJsonLd)} />
        <script {...jsonLdScriptProps(orgJsonLd)} />
        <script {...jsonLdScriptProps(appJsonLd)} />
        <script {...jsonLdScriptProps(navJsonLd)} />
        <script {...jsonLdScriptProps(pageFactsJsonLd)} />
        
        {/* Theme initialization - prevent flash of unstyled content.
            Writes the resolved theme to localStorage so next-themes resolves
            immediately on mount instead of returning undefined during hydration. */}
        <script
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var key = 'megilance-theme';
                  var stored = localStorage.getItem(key);
                  var theme = (stored === 'dark' || stored === 'light') ? stored : (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
                  try { localStorage.setItem(key, theme); } catch (_) {}
                  document.documentElement.classList.remove('light', 'dark');
                  document.documentElement.classList.add(theme);
                  document.documentElement.style.colorScheme = theme;
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body className="bg-[var(--background)] text-[var(--text-primary)] antialiased">
        <a href="#main-content" className="sr-only focus:not-sr-only focus:absolute focus:z-[9999] focus:p-4 focus:bg-[var(--primary)] focus:text-white top-0 left-0">Skip to main content</a>
        <ClientRoot>
          {children}
        </ClientRoot>
      </body>
    </html>
  );
}
